[pytest]
addopts = -ra
python_files = test_*.py
python_classes = Test*
python_functions = test_*
testpaths = testing_formal/tests
markers =
    unit: unit tests
    integration: integration tests
    system: system-level tests
