# -------------------------
# DRAFT MANAGER (ENHANCED)
# -------------------------
"""
Enhanced Draft Manager that integrates with Tone Preference system.
Maintains backward compatibility while adding tone-aware draft generation.
"""

# -------------------------
# IMPORTS
# -------------------------
from typing import Dict, Any, Optional
from src.backend.services.ai_service import OllamaService
from src.backend.models.tone_models import ToneType


class DraftManager:
    """Enhanced AI component for managing and generating message drafts with tone awareness."""
    
    def __init__(self, ai_service: OllamaService, tone_engine=None, tone_manager=None):
        self.ai_service = ai_service
        # Prefer tone_engine naming; keep tone_manager input for backward compatibility.
        self.tone_engine = tone_engine if tone_engine is not None else tone_manager
    
    async def generate_draft(self, message_context: str, tone: Optional[ToneType] = None) -> str:
        """
        Generate draft with optional tone specification.
        
        Args:
            message_context: Context for draft generation
            tone: Optional tone for the draft
            
        Returns:
            Generated draft text
        """
        if tone and self.tone_engine:
            # Use tone-aware generation
            return await self._generate_tone_aware_draft(message_context, tone)
        else:
            # Legacy draft generation
            return await self._generate_basic_draft(message_context)
    
    async def _generate_tone_aware_draft(self, message_context: str, tone: ToneType) -> str:
        """
        Generate draft with specific tone using tone preference engine.
        """
        try:
            # Create message data for tone processing
            message_data = {
                'content': message_context,
                'source': 'draft_generation'
            }
            
            # Use tone preference engine for generation
            result = await self.tone_engine.process_outgoing_message(
                original_message=message_data,
                draft_text="",  # Generate from scratch
                manual_tone=tone
            )
            
            return result.get('adjusted_draft', 'Draft generated by AI...')
            
        except Exception as e:
            print(f"Error in tone-aware draft generation: {e}")
            return await self._generate_basic_draft(message_context)
    
    async def _generate_basic_draft(self, message_context: str) -> str:
        """
        Basic draft generation (legacy compatibility).
        """
        try:
            prompt = f"""
            Generate a professional email draft based on this context:
            
            {message_context}
            
            Requirements:
            - Be clear and concise
            - Use professional language
            - Include appropriate greeting and closing
            - Address the main points
            
            Draft:
            """
            
            draft = await self.ai_service.generate_summary_async(prompt)
            return draft.strip() if draft else "Draft generated by AI..."
            
        except Exception as e:
            print(f"Error in basic draft generation: {e}")
            return "Draft generated by AI..."
    
    async def process_reply_draft(self, original_message: Dict[str, Any], 
                               user_draft: str = "",
                               manual_tone: Optional[ToneType] = None) -> Dict[str, Any]:
        """
        Process reply draft with tone adjustment.
        
        Args:
            original_message: Message being replied to
            user_draft: User's initial draft (optional)
            manual_tone: User-selected tone (optional)
            
        Returns:
            Dictionary with processed draft and metadata
        """
        if not self.tone_engine:
            # Fallback to basic processing
            return {
                'draft': user_draft or await self._generate_basic_draft(str(original_message)),
                'tone': manual_tone or ToneType.FORMAL,
                'confidence': 0.5,
                'reasoning': 'Basic draft generation (no tone engine)'
            }
        
        # Use tone preference engine for processing
        result = await self.tone_engine.process_outgoing_message(
            original_message=original_message,
            draft_text=user_draft,
            manual_tone=manual_tone
        )
        
        return {
            'draft': result.get('adjusted_draft', user_draft),
            'tone': result.get('final_tone', manual_tone or ToneType.FORMAL),
            'recommended_tone': result.get('recommended_tone', ToneType.FORMAL),
            'confidence': result.get('confidence', 0.0),
            'reasoning': result.get('reasoning', ''),
            'tone_detection': result.get('tone_detection')
        }
