# -------------------------
# DRAFT MANAGER 
# -------------------------
"""
Enhanced Draft Manager that integrates with Tone Preference system.
Maintains backward compatibility while adding tone-aware draft generation.
"""

# -------------------------
# IMPORTS
# -------------------------
from typing import Dict, Any, Optional
from src.backend.services.ai_service import OllamaService
from src.backend.models.tone_models import ToneType


class DraftManager:
    """Enhanced AI component for managing and generating message drafts with tone awareness."""
    
    # -------------------------
    # INIT
    # Initializes the class instance and sets up default routing or UI states.
    # -------------------------
    def __init__(self, ai_service: OllamaService, tone_engine=None, tone_manager=None):
        self.ai_service = ai_service
        # Prefer tone_engine naming; keep tone_manager for backward compatibility.
        self.tone_engine = tone_engine if tone_engine is not None else tone_manager
    
    # -------------------------
    # GENERATE DRAFT
    # Creates and returns draft.
    # -------------------------
    async def generate_draft(self, message_context: str, tone: Optional[ToneType] = None) -> str:
        """
        Generate draft with optional tone specification.
        
        Args:
            message_context: Context for draft generation
            tone: Optional tone for the draft
            
        Returns:
            Generated draft text
        """
        if tone and self.tone_engine:
            # Use tone-aware generation
            return await self._generate_tone_aware_draft(message_context, tone)
        else:
            # Legacy draft generation
            return await self._generate_basic_draft(message_context)
    
    # -------------------------
    # GENERATE TONE AWARE DRAFT
    # Creates and returns tone aware draft.
    # -------------------------
    async def _generate_tone_aware_draft(self, message_context: str, tone: ToneType) -> str:
        """
        Generate draft with specific tone using tone preference engine.
        """
        try:
            # Create message data for tone processing
            message_data = {
                'content': message_context,
                'source': 'draft_generation'
            }
            
            # Use tone preference engine for generation
            result = await self.tone_engine.process_outgoing_message(
                original_message=message_data,
                draft_text="",  # Generate from scratch
                manual_tone=tone
            )
            
            return result.get('adjusted_draft', 'Draft generated by AI...')
            
        except Exception as e:
            print(f"Error in tone-aware draft generation: {e}")
            return await self._generate_basic_draft(message_context)
    
    # -------------------------
    # GENERATE BASIC DRAFT
    # Creates and returns basic draft.
    # -------------------------
    async def _generate_basic_draft(self, message_context: str, message_data: dict = None) -> str:
        """
        Context-aware draft generation using actual message content.
        """
        try:
            sender = ""
            subject = ""
            body = message_context
            task_type = ""

            if message_data:
                sender = message_data.get('sender', '')
                subject = message_data.get('subject', message_data.get('content_preview', ''))
                body = message_data.get('full_content', message_data.get('preview', message_context))
                ai_tasks = message_data.get('ai_tasks', [])
                task_type = ai_tasks[0] if ai_tasks else ''

            if not body:
                body = message_context

            # Build a task-specific instruction
            task_instruction = ""
            if task_type == "File Attachment Required":
                task_instruction = "The sender is requesting a file or document. Acknowledge the request and let them know when you will send it."
            elif task_type == "Draft Generation":
                task_instruction = "This requires a detailed, thoughtful, and composed reply that directly addresses all points raised."
            elif task_type == "Auto Reply":
                task_instruction = "This is a transactional or notification message. A brief, polite acknowledgement is sufficient."
            elif task_type == "Simple Reply Required":
                task_instruction = "A short, direct, and friendly reply is expected. Address the question or request concisely."
            else:
                task_instruction = "Provide a professional, helpful, and complete reply."

            sender_line = f"From: {sender}" if sender else ""
            subject_line = f"Subject: {subject}" if subject else ""

            prompt = f"""You are a professional email assistant. Write a reply to the following message.

{sender_line}
{subject_line}

---
{body[:1500]}
---

Instructions:
- {task_instruction}
- Start with an appropriate greeting (e.g., "Hi [Name]," or "Dear [Name],")
- Directly address the specific content and questions in the message above
- Do NOT use placeholder text like "[Your Name]" or "[Details]"
- End with a professional closing like "Best regards,"
- Keep the reply focused and relevant to exactly what was asked
- Do NOT add unnecessary generic filler

Reply:"""

            draft = await self.ai_service.generate_text_async(prompt, temperature=0.4, max_tokens=350)
            return draft.strip() if draft else "Thanks for your message. I will get back to you shortly."

        except Exception as e:
            print(f"Error in draft generation: {e}")
            return "Thank you for your message. I'll review it and get back to you shortly."

    # -------------------------
    # GENERATE CONFLICT REPLY
    # Creates and returns conflict reply.
    # -------------------------
    async def generate_conflict_reply(self, message_data: dict, conflicting_event_title: str,
                                       conflicting_start: str, conflicting_end: str) -> str:
        """
        Generate a polite reply informing the sender about a calendar conflict,
        suggesting to reschedule.
        """
        try:
            sender = message_data.get('sender', 'there')
            subject = message_data.get('subject', message_data.get('content_preview', 'your meeting request'))
            body = message_data.get('full_content', message_data.get('preview', ''))

            prompt = f"""You are a professional email assistant. Write a polite reply to decline a meeting/event request because the calendar slot is already busy.

From: {sender}
Subject: {subject}
---
{body[:800]}
---

Existing calendar conflict:
- Event: "{conflicting_event_title}"
- Time: {conflicting_start} to {conflicting_end}

Instructions:
- Politely inform the sender that you already have another appointment/meeting at that time
- Mention the rough time of your existing commitment without oversharing details
- Suggest rescheduling or ask them to propose an alternative time
- Keep the tone warm and professional
- Do NOT use placeholder text
- Start with a proper greeting and end with a professional closing

Reply:"""

            draft = await self.ai_service.generate_text_async(prompt, temperature=0.4, max_tokens=250)
            if draft and draft.strip():
                return draft.strip()

            # Fallback polite reply
            return (
                f"Hi {sender.split()[0] if sender else 'there'},\n\n"
                f"Thank you for reaching out regarding '{subject}'.\n\n"
                f"Unfortunately, I already have another appointment scheduled at that time. "
                f"Could we explore an alternative time that works for both of us?\n\n"
                f"Looking forward to finding a suitable slot.\n\nBest regards,"
            )
        except Exception as e:
            print(f"Error generating conflict reply: {e}")
            return (
                "Hi,\n\n"
                "Thank you for the invitation. Unfortunately, I already have an existing appointment "
                "at that time. Could we arrange an alternative time?\n\nBest regards,"
            )

    
    # -------------------------
    # PROCESS REPLY DRAFT
    # Executes processing logic for reply draft.
    # -------------------------
    async def process_reply_draft(self, original_message: Dict[str, Any], 
                               user_draft: str = "",
                               manual_tone: Optional[ToneType] = None) -> Dict[str, Any]:
        """
        Process reply draft with tone adjustment.
        
        Args:
            original_message: Message being replied to
            user_draft: User's initial draft (optional)
            manual_tone: User-selected tone (optional)
            
        Returns:
            Dictionary with processed draft and metadata
        """
        if not self.tone_engine:
            # Fallback to basic processing
            return {
                'draft': user_draft or await self._generate_basic_draft(str(original_message)),
                'tone': manual_tone or ToneType.FORMAL,
                'confidence': 0.5,
                'reasoning': 'Basic draft generation (no tone engine)'
            }
        
        # Use tone preference engine for processing
        result = await self.tone_engine.process_outgoing_message(
            original_message=original_message,
            draft_text=user_draft,
            manual_tone=manual_tone
        )
        
        return {
            'draft': result.get('adjusted_draft', user_draft),
            'tone': result.get('final_tone', manual_tone or ToneType.FORMAL),
            'recommended_tone': result.get('recommended_tone', ToneType.FORMAL),
            'confidence': result.get('confidence', 0.0),
            'reasoning': result.get('reasoning', ''),
            'tone_detection': result.get('tone_detection')
        }
