"""
Gmail Agent - Intelligent wrapper around Gmail backend service.
Adds AI capabilities: summarization, priority scoring, draft generation.
"""
import os
import asyncio
from typing import List, Dict, Optional
from src.backend.agents.base_agent import BaseAgent
from src.backend.models.agent_models import AgentRequest, AgentResponse, Intent
from src.backend.services.gmail_backend import GmailIntegrationService
from src.backend.services.ai_service import OllamaService


class GmailAgent(BaseAgent):
    """Intelligent agent for Gmail management with AI capabilities."""
    
    def __init__(self, ai_service: OllamaService, data_dir: str = None):
        super().__init__(name="gmail_agent")
        
        # Backend service for API calls
        if not data_dir:
            project_root = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..', '..'))
            data_dir = os.path.join(project_root, "data", "gmail_data")
        self.backend = GmailIntegrationService(data_dir=data_dir)
        
        # AI service for intelligence
        self.ai_service = ai_service
        
        print(f"✅ {self.name} initialized with AI capabilities")

    async def process_request(self, request: AgentRequest) -> AgentResponse:
        """Process Gmail related requests with AI intelligence."""
        try:
            if request.intent == Intent.FETCH_MESSAGES:
                return await self._handle_fetch(request)
            
            elif request.intent == Intent.SEND_MESSAGE:
                return await self._handle_send(request)
            
            elif request.intent == Intent.SUMMARIZE:
                return await self._handle_summarize(request)
            
            elif request.intent == Intent.ANALYZE_PRIORITY:
                return await self._handle_priority(request)
                
            else:
                return self.error_response(f"Unsupported intent: {request.intent}")

        except Exception as e:
            return self.error_response(f"Gmail agent error: {str(e)}")

    async def _handle_fetch(self, request: AgentRequest) -> AgentResponse:
        """Fetch emails and add AI intelligence."""
        import asyncio # Local import to ensure availability
        if not self.backend or not self.backend.is_connected:
            print("❌ Gmail Agent: Backend not connected")
            return self.error_response("Gmail not connected. Please authorize Gmail in Settings.")
            
        max_results = request.parameters.get("max_results", 25)
        query = request.parameters.get("query", "in:inbox")
        add_ai = request.parameters.get("add_ai_analysis", True)
        
        print(f"🔍 Gmail Agent: Syncing Gmail (max={max_results}, ai={add_ai})...")
        
        try:
            # Step 1: Fetch raw messages (synchronous API call)
            messages = self.backend.fetch_messages(max_results=max_results, query=query)
            print(f"📊 Gmail Agent: Fetched {len(messages)} messages from backend")
            
            if not messages:
                return self.success_response(data={"messages": [], "count": 0})

            # Step 2: Add lightweight AI intelligence (Priority & Tasks)
            # We skip heavy summarization here to return to UI instantly.
            # Summaries will be generated by the frontend QueueSummaryGenerator.
            if add_ai:
                print(f"🤖 Gmail Agent: analyzing priority and tasks for {len(messages)} messages...")
                
                async def process_msg_light(msg):
                    try:
                        # Priority and tasks are fast, so we do them now
                        msg['ai_priority_score'] = await self._analyze_priority(msg)
                        msg['ai_tasks'] = await self._extract_tasks(msg)
                        # Mark for background summarization
                        if not msg.get('summary'):
                             msg['summary'] = "" 
                    except Exception as e:
                        print(f"⚠️ Error processing message {msg.get('id')}: {e}")
                    return msg

                # Run parallel processing for lightweight tasks
                processed_messages = await asyncio.gather(*[process_msg_light(m) for m in messages], return_exceptions=True)
                
                # Filter out exceptions if any
                messages = [m for m in processed_messages if isinstance(m, dict)]
                
                print("✅ Gmail Agent: Initial processing complete")

            return self.success_response(data={"messages": messages, "count": len(messages)})
            
        except Exception as e:
            print(f"❌ Gmail Agent: Fetch failed: {e}")
            return self.error_response(str(e))


    async def _handle_send(self, request: AgentRequest) -> AgentResponse:
        """Send email or reply."""
        # Implement send logic using backend
        return self.error_response("Send functionality not yet implemented")

    async def _handle_summarize(self, request: AgentRequest) -> AgentResponse:
        """Generate AI summary for a specific message."""
        message = request.parameters.get("message")
        if not message:
            return self.error_response("No message provided for summarization")
        
        summary = await self._generate_summary(message)
        return self.success_response(data={"summary": summary})

    async def _handle_priority(self, request: AgentRequest) -> AgentResponse:
        """Analyze priority for a message."""
        message = request.parameters.get("message")
        if not message:
            return self.error_response("No message provided for priority analysis")
        
        priority_score = await self._analyze_priority(message)
        return self.success_response(data={"priority_score": priority_score})

    async def _generate_summary(self, message: Dict) -> str:
        """Use AI to generate summary of email."""
        try:
            # Prefer full content, fallback to snippet/preview
            content = message.get('full_content') or message.get('preview') or message.get('snippet') or message.get('subject', '')
            
            if not content or len(content.strip()) < 10:
                print(f"⚠️ Skipping summary for {message.get('id')}: Content too short")
                return "No content to summarize"
            
            print(f"📝 Summarizing email {message.get('id')[:8]}...")
            
            # Use AI service asynchronously
            summary = await self.ai_service.generate_summary_async(content, sender=message.get('sender', ''), subject=message.get('subject', ''))
            return summary or "Summary unavailable"
        except Exception as e:
            print(f"❌ Summary generation failed for {message.get('id')}: {e}")
            return "Summary unavailable"

    async def _analyze_priority(self, message: Dict) -> float:
        """Use AI to analyze email priority (0.0 to 1.0)."""
        try:
            # Simple heuristic for now - can be replaced with AI prompt
            subject = message.get('subject', '').lower()
            content = message.get('full_content', '').lower()
            
            urgent_keywords = ['urgent', 'asap', 'immediately', 'critical', 'emergency']
            high_keywords = ['important', 'priority', 'deadline', 'action required']
            
            score = 0.3  # Base score
            
            for keyword in urgent_keywords:
                if keyword in subject or keyword in content:
                    score = max(score, 0.9)
                    break
            
            for keyword in high_keywords:
                if keyword in subject or keyword in content:
                    score = max(score, 0.7)
                    break
            
            return min(score, 1.0)
        except Exception as e:
            print(f"Priority analysis failed: {e}")
            return 0.5

    async def _extract_tasks(self, message: Dict) -> List[str]:
        """Use AI to extract actionable tasks from email."""
        try:
            # Placeholder - can use AI prompt to extract tasks
            return []
        except Exception as e:
            print(f"Task extraction failed: {e}")
            return []

    def connect(self, allow_flow: bool = True) -> tuple[bool, str]:
        """Connect to Gmail using backend service."""
        return self.backend.connect(allow_flow=allow_flow)

    def has_token(self) -> bool:
        """Check if Gmail is authenticated."""
        return self.backend.has_token()
